# Service: Mengelola akses ke aplikasi dalam cluster Kubernetes
apiVersion: v1 # Versi API Kubernetes yang digunakan
kind: Service # Jenis sumber daya yang dibuat, yaitu Service
metadata: # Metadata untuk identifikasi objek
  name: order-service # Nama objek Service
  labels: # Label untuk mengelompokkan dan mengidentifikasi resource
    app: order-service
    tier: producer
spec: # Spesifikasi konfigurasi Service
  selector: # Menentukan Pod mana yang harus dilayani oleh Service ini
    app: order-service
    tier: producer
  ports: # Konfigurasi port yang diekspos oleh Service
    - name: http-nodejs # Nama port yang digunakan
      port: 3000 # Port yang dapat diakses dalam cluster
---
# Deployment: Mengelola replikasi dan pembaruan aplikasi
apiVersion: apps/v1 # Versi API Kubernetes yang digunakan
kind: Deployment # Jenis sumber daya yang dibuat, yaitu Deployment
metadata: # Metadata untuk identifikasi objek
  name: order-service # Nama objek Deployment
  labels: # Label untuk mengelompokkan dan mengidentifikasi resource
    app: order-service
    tier: producer
spec: # Spesifikasi konfigurasi Deployment
  replicas: 1 # Menentukan jumlah replika Pod yang akan dibuat
  selector: # Menentukan Pod mana yang akan dikelola oleh Deployment
    matchLabels:
      app: order-service
      tier: producer
  template: # Template untuk membuat Pod yang dikelola oleh Deployment
    metadata: # Metadata untuk identifikasi Pod
      labels: # Label yang diterapkan pada Pod
        app: order-service
        tier: producer
    spec: # Spesifikasi konfigurasi Pod
      containers: # Daftar kontainer dalam Pod
        - name: order-service # Nama kontainer dalam Pod
          image: ghcr.io/mzaedan/order-service:latest # Image Docker yang digunakan untuk kontainer
          ports: # Konfigurasi port yang digunakan oleh kontainer
            - containerPort: 3000 # Port yang digunakan dalam kontainer
          env: # Daftar variabel environment yang digunakan dalam kontainer
            - name: AMQP_PASSWORD # Variabel untuk menyimpan password AMQP
              valueFrom:
                secretKeyRef: # Mengambil nilai dari Secret Kubernetes
                  name: rabbitmq # Nama Secret yang digunakan
                  key: rabbitmq-password # Kunci yang berisi password RabbitMQ
            - name: AMQP_URL # Variabel untuk alamat URL RabbitMQ
              value: "amqp://user:$(AMQP_PASSWORD)@rabbitmq-headless:5672/" # Format URL koneksi ke RabbitMQ
