apiVersion: v1 # Versi API Kubernetes yang digunakan
kind: PersistentVolume # Mendefinisikan sumber daya PersistentVolume (PV)
metadata: # Informasi metadata untuk identifikasi objek
  name: karsajobs-db-pv # Nama PersistentVolume
  labels: # Label untuk klasifikasi dan pengelompokan
    type: local # Menandakan bahwa volume bersifat lokal
spec: # Spesifikasi konfigurasi PersistentVolume
  storageClassName: manual # Menentukan storage class dengan nama "manual"
  capacity: # Kapasitas penyimpanan yang dialokasikan
    storage: 1Gi # Menyediakan ruang penyimpanan sebesar 1 GiB
  accessModes: # Mode akses untuk penggunaan volume
    - ReadWriteOnce # Volume dapat dibaca dan ditulis oleh satu Node dalam satu waktu
  hostPath: # Menentukan lokasi penyimpanan pada host
    path: /mnt/data # Direktori penyimpanan di host
---
apiVersion: v1 # Versi API Kubernetes yang digunakan
kind: PersistentVolumeClaim # Mendefinisikan sumber daya PersistentVolumeClaim (PVC)
metadata: # Informasi metadata untuk identifikasi objek
  name: karsajobs-db-pvc # Nama PersistentVolumeClaim
spec: # Spesifikasi konfigurasi PersistentVolumeClaim
  storageClassName: manual # Menggunakan storage class dengan nama "manual"
  accessModes: # Mode akses untuk klaim volume
    - ReadWriteOnce # Volume hanya dapat diakses oleh satu Node dalam satu waktu untuk operasi baca/tulis
  resources: # Permintaan sumber daya untuk penyimpanan
    requests: # Menentukan kapasitas penyimpanan yang diminta
      storage: 1Gi # Meminta alokasi penyimpanan sebesar 1 GiB
