apiVersion: v1 # Menentukan versi API Kubernetes yang digunakan
kind: Secret # Jenis sumber daya yang dibuat adalah Secret
metadata:
  name: mongo-db-secret # Nama Secret yang akan digunakan dalam konfigurasi MongoDB
  labels:
    app: mongo # Label untuk pengelompokan atau identifikasi sumber daya

data:
  MONGO_ROOT_USERNAME: YWRtaW4= # Username root MongoDB (encoded dalam base64)
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA== # Password root MongoDB (encoded dalam base64)

type: Opaque # Jenis Secret ini adalah Opaque, yang berarti berisi data yang dienkripsi
